name: Cache Build Workflow

on:
  push:
    branches:
      - main

jobs:
  cache-build:
    name: Create Cache for Build Artifacts
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.0'

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      # Temporarily skip caching to test without conflicts
      # - name: Restore Turborepo build cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .turbo
      #     key: ${{ runner.os }}-turbo-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --mode update-lockfile --verbose
        continue-on-error: false

      - name: Verify Node Modules
        run: ls -la node_modules  # Check if node_modules is present

      - name: Build project
        run: yarn run build --verbose
``
