# .github/workflows/use-cache.yaml
name: Use Turbo Cache
on:
  push:
    branches:
      - main

jobs:
  use-turbo-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Turbo Cache
        uses: actions/cache@v4.0.2
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
